
"""AI Life Decision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfqol8GFO3E9SN1yuCsUbglomUFPd9fF
"""

pip install crewai langchain-groq langchain-community

from crewai import Agent

import os
os.environ["GROQ_API_KEY"]="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"

pip install litellm

import os
from crewai import Agent, Task, Crew, LLM
from litellm import RateLimitError
os.environ["GROQ_API_KEY"] = "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"  
llm = LLM(
    model="groq/llama-3.1-8b-instant",
    temperature=0.4,
    max_tokens=500
)

decision = input("💬 Enter your decision: ")
income = input("💰 Monthly income (₹): ")
savings = input("🏦 Total savings (₹): ")
dependents = input("👨‍👩‍👧 Dependents count: ")

user_context = f"""
Decision: {decision}
Monthly Income: {income}
Savings: {savings}
Dependents: {dependents}
"""
profile_agent = Agent(
    role="User Profile Analyst",
    goal="Understand user's mindset, risk tolerance, and personal situation",
    backstory="Expert in behavioral psychology and career decisions",
    llm=llm,
    verbose=True
)

market_agent = Agent(
    role="Market Research Analyst",
    goal="Analyze market risks and opportunities",
    backstory="Expert in startup ecosystems and job markets",
    llm=llm,
    verbose=True
)

financial_agent = Agent(
    role="Financial Advisor",
    goal="Evaluate financial stability and risk",
    backstory="Expert in personal finance and risk planning",
    llm=llm,
    verbose=True
)

final_decision_agent = Agent(
    role="Final Decision Maker",
    goal="Combine all insights and give a final structured recommendation",
    backstory="Senior strategist combining profile, market, and financial insights",
    llm=llm,
    verbose=True
)
task1 = Task(
    description=f"""
Analyze the user profile:
{user_context}

Output:
- Personality type
- Risk tolerance
- Decision mindset
""",
    expected_output="Structured profile analysis with personality, risk level, and mindset",
    agent=profile_agent
)

task2 = Task(
    description=f"""
Analyze market conditions for:
{decision}

Output:
- Growth opportunities
- Risks
- Industry trends
""",
    expected_output="Market trends, risks, and opportunities",
    agent=market_agent
)

task3 = Task(
    description=f"""
Analyze financial condition:
{user_context}

Output:
- Financial stability
- Survival months estimation
- Risk level (Low/Medium/High)
""",
    expected_output="Financial stability, survival months, and risk level",
    agent=financial_agent
)

task4 = Task(
    description="""
Combine the outputs of Profile Agent, Market Agent, and Financial Agent.

Provide:
- Pros
- Cons
- Risk Level
- Final Recommendation

Make it structured and practical for the user decision.
""",
    expected_output="Final structured decision with pros, cons, risk level, and recommendation",
    agent=final_decision_agent
)
crew = Crew(
    agents=[profile_agent, market_agent, financial_agent, final_decision_agent],
    tasks=[task1, task2, task3, task4],
    verbose=True,
    retry=False,       
    max_retries=0
)
def safe_crew_run(crew_obj):
    try:
        return crew_obj.kickoff()
    except RateLimitError:
        return "⚠ Unable to complete task: API rate limit reached. Please try later."
    except Exception as e:
        return f"⚠ Task failed due to unexpected error: {e}"
result = safe_crew_run(crew)
print("\n🧠 FINAL OUTPUT:\n")
print(result)

import os
from crewai import Agent, Task, Crew, LLM
os.environ["GROQ_API_KEY"] = "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"  # Replace with your real key

llm_base = LLM(
    model="groq/llama-3.1-8b-instant",
    temperature=0.4,
    max_tokens=500
)
decision = input("💬 Enter your decision: ")
income = input("💰 Monthly income (₹): ")
savings = input("🏦 Total savings (₹): ")
dependents = input("👨‍👩‍👧 Dependents count: ")
user_context = f"""
Decision: {decision}
Monthly Income: {income}
Savings: {savings}
Dependents: {dependents}
"""
profile_agent = Agent(
    role="User Profile Analyst",
    goal="Understand user's mindset, risk tolerance, and personal situation",
    backstory="Expert in behavioral psychology and career decisions",
    llm=llm_base,
    verbose=True
)

market_agent = Agent(
    role="Market Research Analyst",
    goal="Analyze market risks and opportunities",
    backstory="Expert in startup ecosystems and job markets",
    llm=llm_base,
    verbose=True
)

financial_agent = Agent(
    role="Financial Advisor",
    goal="Evaluate financial stability and risk",
    backstory="Expert in personal finance and risk planning",
    llm=llm_base,
    verbose=True
)
final_decision_agent = Agent(
    role="Final Decision Maker",
    goal="Combine all insights and give a final structured recommendation",
    backstory="Senior strategist combining profile, market, and financial insights",
    llm=LLM(
        model="groq/llama-3.1-8b-instant",
        temperature=0.4,
        max_tokens=1200  # Increased to prevent truncation
    ),
    verbose=True
)
task1 = Task(
    description=f"""
Analyze the user profile:
{user_context}

Output:
- Personality type
- Risk tolerance
- Decision mindset
""",
    expected_output="Structured profile analysis with personality, risk level, and mindset",
    agent=profile_agent
)

task2 = Task(
    description=f"""
Analyze market conditions for:
{decision}

Output:
- Growth opportunities
- Risks
- Industry trends
""",
    expected_output="Market trends, risks, and opportunities",
    agent=market_agent
)

task3 = Task(
    description=f"""
Analyze financial condition:
{user_context}

Output:
- Financial stability
- Survival months estimation
- Risk level (Low/Medium/High)
""",
    expected_output="Financial stability, survival months, and risk level",
    agent=financial_agent
)

task4 = Task(
    description="""
Combine the outputs of Profile Agent, Market Agent, and Financial Agent.

Provide a clear and complete recommendation:
- Pros
- Cons
- Risk Level
- Final Recommendation (write in complete sentences, full paragraph)

Make it structured and practical for the user decision.
""",
    expected_output="Final structured decision with pros, cons, risk level, and full recommendation paragraph",
    agent=final_decision_agent
)

crew = Crew(
    agents=[profile_agent, market_agent, financial_agent, final_decision_agent],
    tasks=[task1, task2, task3, task4],
    verbose=True,
    retry=False,
    max_retries=0
)

result = crew.kickoff()

print("\n🧠 FINAL OUTPUT:\n")
print(result)

import os
from crewai import Agent, Task, Crew, LLM
os.environ["GROQ_API_KEY"] = "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"
llm = LLM(
    model="groq/llama-3.1-8b-instant",
    temperature=0.4,
    max_tokens=500
)

decision = input("💬 Enter your decision: ")
income = input("💰 Monthly income (₹): ")
savings = input("🏦 Total savings (₹): ")
dependents = input("👨‍👩‍👧 Dependents count: ")
user_context = f"""
Decision: {decision}
Monthly Income: {income}
Savings: {savings}
Dependents: {dependents}
"""
profile_agent = Agent(
    role="User Profile Analyst",
    goal="Understand user's mindset, risk tolerance, and personal situation",
    backstory="Expert in behavioral psychology and career decisions",
    llm=llm,
    verbose=False
)
financial_agent = Agent(
    role="Financial Advisor",
    goal="Evaluate financial stability and risk",
    backstory="Expert in personal finance and risk planning",
    llm=llm,
    verbose=False
)
final_decision_agent = Agent(
    role="Final Decision Maker",
    goal="Combine all insights and give a final recommendation",
    backstory="Senior strategist combining profile and financial insights",
    llm=llm,
    verbose=False
)
task1 = Task(
    description=f"""
Analyze the user profile:
{user_context}

Output:
- Personality type
- Risk tolerance
- Decision mindset
""",
    expected_output="Structured profile analysis",
    agent=profile_agent
)
task2 = Task(
    description=f"""
Analyze financial condition:
{user_context}

Output:
- Financial stability
- Survival months estimation
- Risk level (Low/Medium/High)
""",
    expected_output="Financial stability and risk assessment",
    agent=financial_agent
)
task3 = Task(
    description=f"""
Evaluate the user's decision:
Decision: {decision}

Use insights from profile and financial analysis.

Output:
- Recommendation (Correct / Wrong)
- Reasoning (Brief explanation)
""",
    expected_output="Final verdict on decision",
    agent=final_decision_agent
)
crew = Crew(
    agents=[profile_agent, financial_agent, final_decision_agent],
    tasks=[task1, task2, task3],
    verbose=True,
    retry=False,
    max_retries=0
)
result = crew.kickoff()
print("\n🧠 FINAL DECISION OUTPUT:\n")
print(result)
